# Generated by Django 5.1.6 on 2025-04-23 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0003_remove_store_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Bữa sáng"),
                            ("LUNCH", "Bữa trưa"),
                            ("DINNER", "Bữa tối"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "foods",
                    models.ManyToManyField(related_name="menus", to="foods.food"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menus",
                        to="foods.store",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
