# Generated by Django 5.1.6 on 2025-05-03 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('MOMO', 'Momo'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('ZALOPAY', 'ZaloPay')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PROCESSING', 'Đang xử lý'), ('COMPLETED', 'Đã thanh toán'), ('FAILED', 'Thanh toán thất bại'), ('REFUNDED', 'Đã hoàn tiền')], default='PENDING', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_url', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='foods.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
