# Generated by Django 5.1.6 on 2025-05-15 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0005_remove_order_payment_method_alter_order_total_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Tiền mặt"),
                    ("MOMO", "Momo"),
                    ("PAYPAL", "PayPal"),
                    ("STRIPE", "Stripe"),
                    ("ZALOPAY", "ZaloPay"),
                ],
                default="CASH",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="foods.food"
            ),
        ),
    ]
