# Generated by Django 5.1.6 on 2025-05-18 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0006_remove_order_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="foods.food",
            ),
        ),
    ]
