# Generated by Django 5.1.6 on 2025-06-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0007_alter_review_food"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
